# Generated by Django 6.0.6 on 2026-08-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='max_active_orders',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
