# Generated by Django 6.0.6 on 2026-08-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryboyprofile_max_active_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoyOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'used'], name='delivery_de_phone_f79999_idx')],
            },
        ),
    ]
