# Generated by Django 6.0.6 on 2026-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryboyotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='payment_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/payment_proofs/'),
        ),
    ]
