# Generated by Django 6.0.6 on 2026-09-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryassignment_collected_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryassignment',
            options={'ordering': ['-assigned_at', '-id']},
        ),
    ]
