# Generated by Django 6.0.6 on 2026-07-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-featured', 'display_order', '-priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discountusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='discount',
            name='badge_text',
            field=models.CharField(default='SALE', max_length=40),
        ),
        migrations.AddField(
            model_name='discount',
            name='banner_color',
            field=models.CharField(default='#FF9800', max_length=20),
        ),
        migrations.AddField(
            model_name='discount',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/'),
        ),
        migrations.AddField(
            model_name='discount',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='notification_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='notification_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
