# Generated by Django 6.0.6 on 2026-07-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_coupon_couponusage_discountusage_discount_type_and_more'),
        ('shops', '0004_shop_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponusage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='shops.shop'),
        ),
    ]
