# Generated by Django 6.0.6 on 2026-06-16 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='total_cancellations',
            new_name='total_cancelled_orders',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_completed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='total_rejected_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_flags', to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
