# Generated by Django 6.0.6 on 2026-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managerprofile_address_managerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('customer', 'Customer'), ('delivery_boy', 'Delivery Boy')], default='customer', max_length=20),
        ),
    ]
