# Generated by Django 6.0.6 on 2026-09-11 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customerdeliveryaddress'),
        ('shops', '0008_shop_delivery_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('preparing_staff', 'Preparing Staff'), ('customer', 'Customer'), ('delivery_boy', 'Delivery Boy')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='PreparingStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='preparing_staff/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparing_staff', to='shops.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparing_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
