# Generated by Django 6.0.6 on 2026-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_latitude_shop_longitude_shopmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
