# Generated by Django 6.0.6 on 2026-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_shop_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_assignment_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Maximum delivery radius in kilometers', max_digits=6),
        ),
    ]
