# Generated by Django 6.0.6 on 2026-09-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_order_capacity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopordercapacityaudit',
            new_name='shops_shopo_shop_id_930b0f_idx',
            old_name='shops_shop_id_5a7f13_idx',
        ),
    ]
