# Generated by Django 6.0.6 on 2026-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_shop_delivery_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='upi_id',
            field=models.CharField(blank=True, default='rotiwala@upi', help_text='Shop UPI Virtual Payment Address (e.g. shop@okhdfcbank)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='upi_qr_image',
            field=models.ImageField(blank=True, help_text='Shop static or dynamic UPI QR Code Image', null=True, upload_to='shops/upi_qr/'),
        ),
    ]
