# Generated by Django 6.0.6 on 2026-06-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['name'], 'verbose_name': 'Menu Category', 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
