# Generated by Django 6.0.6 on 2026-06-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menucategory_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='updated_at',
        ),
    ]
