# Generated by Django 6.0.6 on 2026-06-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_is_available'),
        ('shops', '0003_shop_latitude_shop_longitude_shopmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shops.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='shops.shop'),
            preserve_default=False,
        ),
    ]
