# Generated by Django 6.0.6 on 2026-08-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menucategory_shop_menuitem_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='shop',
        ),
    ]
