# Generated by Django 6.0.6 on 2026-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_collection_time_order_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='collection_time',
            new_name='pickup_time',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash On Pickup'), ('upi', 'UPI On Shop')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
