# Generated by Django 6.0.6 on 2026-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_collection_time_order_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
