# Generated by Django 6.0.6 on 2026-06-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_estimated_minutes_order_estimated_ready_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_person_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
