# Generated by Django 6.0.6 on 2026-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pickup_person_name_order_pickup_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_by_other_person',
            field=models.BooleanField(default=False),
        ),
    ]
