# Generated by Django 6.0.6 on 2026-06-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_paid_at_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkincart',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
