# Generated by Django 6.0.6 on 2026-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_walkincart_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_type',
            field=models.CharField(choices=[('instant', 'Prepare Immediately'), ('scheduled', 'Scheduled Pickup')], default='instant', max_length=20),
        ),
    ]
