# Generated by Django 6.0.6 on 2026-07-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_couponusage_shop'),
        ('orders', '0011_rename_item_price_orderitem_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_type',
            field=models.CharField(choices=[('none', 'None'), ('discount', 'Discount'), ('coupon', 'Coupon')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion_type',
            field=models.CharField(choices=[('none', 'None'), ('discount', 'Discount'), ('coupon', 'Coupon')], default='none', max_length=20),
        ),
    ]
