# Generated by Django 6.0.6 on 2026-08-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_delivery_address_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkincart',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='walkincart',
            name='token_number',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
