# Generated by Django 6.0.6 on 2026-09-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_capacity_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_shop_id_032e22_idx',
            old_name='orders_shop_id_8d5e4e_idx',
        ),
    ]
