# Generated by Django 6.0.6 on 2026-09-11 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_couponusage_shop'),
        ('orders', '0016_rename_orders_shop_id_8d5e4e_idx_orders_orde_shop_id_032e22_idx'),
        ('shops', '0008_shop_delivery_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, help_text='Business date for token sequencing', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, db_index=True, help_text='Sequential walk-in token number for the day', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'business_date', 'status'], name='orders_orde_shop_id_8d2893_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['token_number'], name='orders_orde_token_n_bc3282_idx'),
        ),
    ]
