# Generated by Django 6.0.6 on 2026-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_business_date_order_token_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Customer UPI or payment transaction proof photo', null=True, upload_to='orders/payment_proofs/'),
        ),
    ]
