# Generated by Django 6.0.6 on 2026-09-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated unique UUID for idempotent order placement', max_length=64, null=True, unique=True),
        ),
    ]
