# Generated by Django 6.0.6 on 2026-10-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitemvariant'),
        ('orders', '0019_order_client_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitemvariant'),
        ),
        migrations.AddField(
            model_name='walkincartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitemvariant'),
        ),
    ]
