# Generated by Django 6.0.6 on 2026-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderitem_variant_walkincartitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash On Pickup'), ('upi', 'UPI On Shop'), ('credit', 'Credit'), ('parts', 'Split / Part Payment')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='walkincart',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash On Pickup'), ('upi', 'UPI On Shop'), ('credit', 'Credit'), ('parts', 'Split / Part Payment')], default='cash', max_length=20),
        ),
    ]
